[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.21"
# https://docs.soliditylang.org/en/v0.8.21/ir-breaking-changes.html#solidity-ir-based-codegen-changes
via_ir = true
# https://docs.soliditylang.org/en/v0.8.21/internals/optimizer.html#optimizer-parameter-runs
optimizer_runs = 5

# from https://github.com/PaulRBerg/foundry-template/blob/main/foundry.toml
[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config